version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: preranams/rvuverse_app:latest  # <--- Image name with your name
    command: gunicorn rvuverse.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
