# Generated by Django 5.2 on 2025-04-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_department_code_alter_post_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='study_year',
            field=models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=10, null=True),
        ),
    ]
